import fs from 'fs-extra';
import path from 'path';
import { Runware } from '@runware/sdk-js';
import dotenv from 'dotenv';
dotenv.config();
/**
 * Service to generate invitation backgrounds using Runware AI.
 */
export const generateBackground = async (prompt, outputPath, width = 1024, height = 1024) => {
    const apiKey = process.env.RUNWARE_API_KEY;
    if (!apiKey || apiKey === 'YOUR_RUNWARE_API_KEY' || apiKey === 'MY_RUNWARE_API_KEY') {
        console.warn('RUNWARE_API_KEY is not configured. Using placeholder background for testing.');
        try {
            // Use a high-quality placeholder from Picsum for testing
            const response = await fetch(`https://picsum.photos/seed/invitation/${width}/${height}`);
            const arrayBuffer = await response.arrayBuffer();
            await fs.ensureDir(path.dirname(outputPath));
            await fs.writeFile(outputPath, Buffer.from(arrayBuffer));
            return outputPath;
        }
        catch (error) {
            throw new Error('Failed to fetch placeholder background: ' + error.message);
        }
    }
    try {
        const runware = new Runware({ apiKey });
        const images = await runware.requestImages({
            positivePrompt: prompt,
            negativePrompt: "text, words, letters, watermark, blurry, low quality",
            width: width,
            height: height,
            numberResults: 1,
            model: "runware:400@1"
        });
        if (!images || images.length === 0) {
            throw new Error("No images generated by Runware");
        }
        const imageUrl = images[0].imageURL;
        // Download the image
        const response = await fetch(imageUrl);
        if (!response.ok) {
            throw new Error(`Failed to download image from Runware: ${response.statusText}`);
        }
        const arrayBuffer = await response.arrayBuffer();
        await fs.ensureDir(path.dirname(outputPath));
        await fs.writeFile(outputPath, Buffer.from(arrayBuffer));
        return outputPath;
    }
    catch (error) {
        console.error('Runware AI Error:', error);
        throw new Error('Failed to generate background image using Runware');
    }
};
